---
- name: Ensure group "nginx-exp" exists
  group:
    name: nginx-exp
    state: present
  become: true

- name: Add user 'nginx-exp' as member of 'nginx-exp' and 'wheel' gourps
  user:
    name: nginx-exp
    shell: /bin/bash
    comment: "nginx user"
    state: present
    group: nginx-exp
  become: true
# get_url – Downloads files from HTTP, HTTPS, or FTP to node
# The remote server must have direct access to the remote resource.
- name: Download nginx-exporter
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: ~/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    mode: 0550
# unarchive – Unpacks an archive after (optionally)
# copying it from the local machine
- name: Extract /etc/nginx-exporter
  become: true
  unarchive:
    src: ~/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true

# template – Template a file out to a remote server
- name: Template a file to /etc/files.conf
  become: true
  template:
    src: template/nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
    owner: nginx-exp
    group: nginx-exp
    mode: 0644

# restart and enable 'nginx_exporter.service'
- name: restart and enable nginx_exporter.server
  become: true
  systemd:
    state: started
    enabled: true
    name: nginx_exporter
