---
- name: fail playbook when GET request to port 9113/metrics does not return 'nginx_up 1'

  uri:
    url: http://localhost:9113/metrics
    method: GET
    return_content: true
  register: webpage
  failed_when: "'nginx_up 1' not in webpage.content"

- name: fail playbook when GET request to port 80 does not return status code 200.
  uri:
    url: http://localhost:80
    method: GET
    return_content: false
  failed_when: "webpage.status != 200"
